### ISSUE TITLE
Build with error

### ISSUE THREAD

**Issue by yunsii** [atinux/my-pull-requests#5]
```
 ERROR  x Build failed in 363ms                                                                                                                                 7:45:45 PM


 ERROR  Nuxt Build Error: [vite:css] [postcss] Cannot find module 'tailwindcss/lib/lib/defaultExtractor.js'                                                     7:45:45 PM
Require stack:
- /home/yuns/my-pull-requests/.nuxt/nuxtui-tailwind.config.cjs
file: /home/yuns/my-pull-requests/node_modules/.pnpm/tailwindcss@3.4.10/node_modules/tailwindcss/tailwind.css:undefined:NaN

  Require stack:
  - .nuxt/nuxtui-tailwind.config.cjs
  file: node_modules/.pnpm/tailwindcss@3.4.10/node_modules/tailwindcss/tailwind.css:undefined:NaN
  at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
  at Function.resolve (node:internal/modules/helpers:190:19)
  at _resolve (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:241814)
  at jiti (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:244531)
  at .nuxt/nuxtui-tailwind.config.cjs:2:60
  at evalModule (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
  at jiti (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)
  at .nuxt/tailwind.config.cjs:7:1
  at evalModule (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:247313)
  at jiti (node_modules/.pnpm/jiti@1.21.6/node_modules/jiti/dist/jiti.js:1:245241)

 ELIFECYCLE  Command failed with exit code 1.
```

It works after I install tailwindcss manually.

**Comment by yunsii** [comment]
Moreover, after add NUXT_GITHUB_TOKEN to project environment, it works as expected
